### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by spoonsol** [xDUDSSx/segment-display-blender-addon#2]
As of at least 4.2, multiple errors come up when clicking "create display". I love this add-on. Please fix it

**Comment by spoonsol** [comment]
![image](https://github.com/user-attachments/assets/c8552ab8-807f-4852-ba0d-989008bbfb0b)

**Comment by xDUDSSx** [comment]
Should be fixed now.

**Comment by spoonsol** [comment]
> Should be fixed now.

It is! Thank you so much for the quick fix.

**Comment by spoonsol** [comment]
It is! Thank you so much!
